### ISSUE TITLE
Where is Credentials.h.template ?

### ISSUE THREAD

**Issue by maumad** [stangreg/Ignitron#21]
"Before building the code, rename the file to Credentials.h and put in your SSID name and WiFi password. After setting up the project in the IDE, the code should build with the standard tool chain."

Where is Credentials.h.template ?

**Comment by stangreg** [comment]
This is from old functionality when Ignitron had an OTA update functionality. This has been removed again for performance reasons. It seems that this bit needs to be removed from the documentation. To build the code, just ignore that part.

**Comment by stangreg** [comment]
Documentation and code base has been cleaned up, closing issue
