### ISSUE TITLE
LEDs 3 and 6 inoperative on WROVER based ESP32 units

### ISSUE THREAD

**Issue by ServError** [stangreg/Ignitron#7]
As pins 16 and 17 are reserved on the WROVER series of ESP32 chips, the two LEDs connected to them by default will not operate. If you have already ordered PCBs, it's necessary to cut and jump to new GPIOs. I tested replacing 16 with 12 and 17 with 15 (and making the corresponding changes in SparkLEDControl.h) and encountered no issues.

Edit - For anyone not in the mood to do the cut and jump that has an unassembled PCB, pull the pins for G16 and G17 out of your female header before installing it on the ignitron board, then jump to those pads.

@stangreg, perhaps a second revision of the pcb with a set of jumper pads that toggles between the original GPIOs and the alternates would have some value. Switching over and leaving an appropriate build switch for the old board is an option too, but could cause some confusion depending on how many old boards are out there.

**Comment by stangreg** [comment]
At this moment, I am not planning to change the hardware design to support additional boards, I am currently only working on software tweaks.
